# Generated by Django 4.0.3 on 2022-03-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_remove_nivel_desenvolvedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.nivel'),
        ),
    ]
