# Generated by Django 4.0.2 on 2022-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_alter_desenvolvedor_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='desenvolvedores',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='developers.Desenvolvedor'),
        ),
    ]
