# Generated by Django 4.0.2 on 2022-03-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0004_nivel_desenvolvedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='developers.nivel'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='desenvolvedores',
            field=models.ManyToManyField(related_name='+', to='developers.Desenvolvedor'),
        ),
    ]
