# Generated by Django 4.0.2 on 2022-03-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_alter_desenvolvedor_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='desenvolvedores',
        ),
    ]
