# Generated by Django 4.0.2 on 2022-03-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0006_remove_nivel_desenvolvedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desenvolvedores', to='developers.nivel'),
        ),
    ]
