# Generated by Django 4.0.2 on 2022-03-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0007_alter_desenvolvedor_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desenvolvedores', to='developers.nivel'),
        ),
    ]
