# Generated by Django 4.0.2 on 2022-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0008_alter_desenvolvedor_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
