# Generated by Django 4.0.2 on 2022-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0009_alter_desenvolvedor_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
