# Generated by Django 4.0.2 on 2022-03-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0010_alter_desenvolvedor_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desenvolvedores', to='developers.nivel'),
        ),
    ]
