# Generated by Django 4.0.2 on 2022-03-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0011_remove_desenvolvedor_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenvolvedor',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desenvolvedores', to='developers.nivel'),
        ),
    ]
